[package]
name = "feather_tnt_run"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
quill = { git = "https://github.com/feather-rs/feather" }
libcraft-core = { git = "https://github.com/feather-rs/feather" }
rand = "0.8.4"
